#!/usr/bin/env sh

# env "PATH=$PATH" allows to resolve 'which node' in sudo mode
# Set Workers to 1 so that only one PhantomJS is launched
sudo env "PATH=$PATH" ./node_modules/.bin/add-to-systemd prerender --env PRERENDER_NUM_WORKERS=1 "$(which node) $(pwd)/prerender.js"
